version: 2
updates:
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/examples/edge-script-repo/.github/workflows"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/examples/tunnel-edge-script-repo/.github/workflows"
    schedule:
      interval: "weekly"
