version: 2
updates:
  - package-ecosystem: "deno"
    directory: "/"
    commit-message:
      prefix: "build(deps)"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/.devcontainer"
    commit-message:
      prefix: "build(deps)"
    ignore:
      - dependency-name: "node"
        update-types:
          - "version-update:semver-major"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "ci(deps)"
    groups:
      codeql-action:
        patterns:
          - "github/codeql-action/*"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/examples/ddns-edge-script-repo/.github/workflows"
    commit-message:
      prefix: "ci(deps)"
    schedule:
      interval: "weekly"
