export type PackageRegistry = "jsr" | "npm";
export type DeployMode = "bunny-git" | "github-action";

export interface ScaffoldOptions {
  projectName: string;
  directory: string;
  packageRegistry: PackageRegistry;
  packageVersion: string;
  deployMode: DeployMode;
  ddnsUsername: string;
  allowedHosts: string;
  allowedZones: string;
  force: boolean;
  dryRun: boolean;
  installDependencies: boolean;
}

export interface ScaffoldResult {
  directory: string;
  files: string[];
}

const DEFAULT_PACKAGE_VERSION = "^1.0.0";

export function defaultOptions(): ScaffoldOptions {
  return {
    projectName: "my-bunny-ddns-edge-script",
    directory: "my-bunny-ddns-edge-script",
    packageRegistry: "jsr",
    packageVersion: DEFAULT_PACKAGE_VERSION,
    deployMode: "bunny-git",
    ddnsUsername: "inadyn",
    allowedHosts: "",
    allowedZones: "",
    force: false,
    dryRun: false,
    installDependencies: true,
  };
}

export async function scaffoldProject(
  options: ScaffoldOptions,
): Promise<ScaffoldResult> {
  const directory = options.directory;
  const files = projectFiles(options);

  if (!options.dryRun) {
    await ensureWritableDirectory(directory, options.force);

    for (const file of files) {
      await rejectSymlinkedOutput(directory, file.path);
    }

    for (const file of files) {
      const path = joinPath(directory, file.path);
      await Deno.mkdir(dirname(path), { recursive: true });
      await Deno.writeTextFile(path, file.content);
    }
  }

  return {
    directory,
    files: files.map((file) => file.path),
  };
}

interface ProjectFile {
  path: string;
  content: string;
}

function projectFiles(options: ScaffoldOptions): ProjectFile[] {
  const files: ProjectFile[] = [
    { path: "deno.json", content: denoJson(options) },
    { path: "script.ts", content: scriptTs() },
    { path: ".env.example", content: envExample(options) },
    { path: ".gitignore", content: gitignore() },
    { path: ".tool-versions", content: "deno 2.9.3\n" },
    { path: "LICENSE", content: mitLicense() },
    { path: "README.md", content: readme(options) },
  ];

  if (options.deployMode === "github-action") {
    files.push({
      path: ".github/workflows/deploy.yml",
      content: deployWorkflow(),
    });
  }

  return files;
}

function denoJson(options: ScaffoldOptions): string {
  const specifier = options.packageRegistry === "jsr"
    ? `jsr:@zimme/bunny-ddns-edge-script@${options.packageVersion}`
    : `npm:@zimme/bunny-ddns-edge-script@${options.packageVersion}`;

  return `${
    JSON.stringify(
      {
        imports: {
          "@bunny.net/edgescript-sdk": "npm:@bunny.net/edgescript-sdk@0.12.1",
          "@zimme/bunny-ddns-edge-script": specifier,
        },
        tasks: {
          build:
            "deno bundle --external @bunny.net/edgescript-sdk script.ts -o generated/script.ts && deno fmt generated/script.ts",
          check: "deno check script.ts",
          ci:
            "deno install --frozen && deno fmt --check && deno lint && deno task check && deno task build",
          fmt: "deno fmt",
          lint: "deno lint",
        },
      },
      null,
      2,
    )
  }\n`;
}

function scriptTs(): string {
  return `import * as BunnySDK from "@bunny.net/edgescript-sdk";
import {
  createBunnyDdnsHandler,
  readBunnyDdnsConfigFromEnv,
} from "@zimme/bunny-ddns-edge-script";

const config = readBunnyDdnsConfigFromEnv({
  get(name: string) {
    return Deno.env.get(name);
  },
});

BunnySDK.net.http.serve(createBunnyDdnsHandler({ config }));
`;
}

function envExample(options: ScaffoldOptions): string {
  return `# Set these as Bunny Edge Script secrets, not committed values.
BUNNY_API_KEY=
DDNS_SHARED_SECRET=

# Optional but recommended.
DDNS_USERNAME=${options.ddnsUsername}
DDNS_ALLOWED_HOSTS=${options.allowedHosts}
DDNS_ALLOWED_ZONES=${options.allowedZones}
DDNS_ALLOW_ALL_HOSTS=${
    options.allowedHosts || options.allowedZones ? "false" : "true"
  }

# Defaults shown here are built in.
DDNS_AUTO_CREATE=true
DDNS_TTL=900
DDNS_MULTI_RECORD_MODE=reject
DDNS_MAX_HOSTNAMES=25
DDNS_MAX_MUTATIONS=40
DDNS_RECORD_COMMENT=Managed by bunny-ddns-edge-script
DDNS_ALLOW_INSECURE_HTTP=false
`;
}

function gitignore(): string {
  return `.env
.env.*
!.env.example
.DS_Store
.bunny/
generated/
node_modules/
`;
}

function readme(options: ScaffoldOptions): string {
  const deploySection = options.deployMode === "bunny-git"
    ? bunnyGitInstructions()
    : githubActionInstructions();

  return `# ${options.projectName}

Personal bunny.net DDNS Edge Script deployment repo.

This repo was generated by \`@zimme/create-bunny-ddns\`. It imports
\`@zimme/bunny-ddns-edge-script\` and builds one deployable Bunny Edge Script
artifact.

## Commands

\`\`\`sh
deno install
deno task check
deno task build
deno task ci
\`\`\`

## Bunny Runtime Secrets

Set these in Bunny Edge Scripting Env Configuration:

- \`BUNNY_API_KEY\`
- \`DDNS_SHARED_SECRET\`
- \`DDNS_USERNAME\`
- Optional: \`DDNS_ALLOWED_HOSTS\`
- Optional: \`DDNS_ALLOWED_ZONES\`

Do not commit real secrets to this repo.
Commit the generated \`deno.lock\` file so deployments remain reproducible.
\`DDNS_ALLOW_ALL_HOSTS=true\` is generated only when no allow-list was supplied;
replace it with \`DDNS_ALLOWED_HOSTS\` or \`DDNS_ALLOWED_ZONES\` for least privilege.

${deploySection}

## Inadyn

\`\`\`conf
custom bunny-ddns-edge-script {
    username       = "${options.ddnsUsername}"
    password       = "your-ddns-shared-secret"

    checkip-server = "ddns.example.com"
    checkip-path   = "/checkip"
    checkip-ssl    = true

    ddns-server    = "ddns.example.com"
    ddns-path      = "/nic/update?hostname=%h&myip=%i"
    ssl            = true

    hostname       = "home.example.com"
}
\`\`\`
`;
}

function bunnyGitInstructions(): string {
  return `## Recommended Deployment: Bunny Git Integration

This path keeps Bunny runtime credentials in Bunny, not GitHub.

1. Push this repo to GitHub.
2. In bunny.net, create a Standalone Edge Script.
3. Connect the Edge Script to this GitHub repository.
4. Configure the Bunny Git deployment settings:

| Setting | Value |
| --- | --- |
| Install command | \`deno install --frozen\` |
| Build command | \`deno task build\` |
| Entry file | \`generated/script.ts\` |

5. Add the runtime secrets in Bunny Edge Script Env Configuration.
6. Deploy the script from Bunny.
7. Point your DDNS hostname or custom script hostname at the deployed script.

The official bunny.net CLI can also link this directory, deploy the built
bundle, and manage Bunny-side configuration:

\`\`\`sh
bunny login
bunny scripts link
deno task build
bunny scripts deploy generated/script.ts
\`\`\`

The CLI stores local script linkage under \`.bunny/\`, which this repo ignores.
`;
}

function githubActionInstructions(): string {
  return `## Deployment: GitHub Action Upload

This path stores only Bunny deployment credentials in GitHub. Runtime secrets
such as \`BUNNY_API_KEY\` and \`DDNS_SHARED_SECRET\` still belong in Bunny Edge
Script Env Configuration.

1. In bunny.net, create a Standalone Edge Script.
2. Add runtime secrets in Bunny Edge Script Env Configuration.
3. Create a Bunny Edge Script deploy key.
4. Add these GitHub repository secrets:
   - \`SCRIPT_ID\`
   - \`DEPLOY_KEY\`
5. Push to \`main\`.
`;
}

function deployWorkflow(): string {
  return `name: Deploy Edge Script

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Setup Deno
        uses: denoland/setup-deno@22d081ff2d3a40755e97629de92e3bcbfa7cf2ed # v2.0.5
        with:
          deno-version: 2.9.3

      - name: Install dependencies
        run: deno install --frozen

      - name: Build deploy artifact
        run: deno task build

      - name: Deploy Script to Bunny Edge Scripting
        uses: BunnyWay/actions/deploy-script@671d620bdaac002d2aa7f3dd0dda03dd99c5b749 # main
        with:
          script_id: \${{ secrets.SCRIPT_ID }}
          deploy_key: \${{ secrets.DEPLOY_KEY }}
          file: generated/script.ts
`;
}

function mitLicense(): string {
  return `MIT License

Copyright (c) 2026 zimme

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
`;
}

async function ensureWritableDirectory(
  directory: string,
  force: boolean,
): Promise<void> {
  try {
    const info = await Deno.lstat(directory);
    if (info.isSymlink) {
      throw new Error(`Target directory "${directory}" cannot be a symlink.`);
    }

    const entries = [];
    for await (const entry of Deno.readDir(directory)) {
      entries.push(entry);
    }

    if (entries.length > 0 && !force) {
      throw new Error(
        `Directory "${directory}" already exists and is not empty. Use --force to write into it.`,
      );
    }
  } catch (error) {
    if (error instanceof Deno.errors.NotFound) {
      await Deno.mkdir(directory, { recursive: true });
      return;
    }

    throw error;
  }
}

async function rejectSymlinkedOutput(
  directory: string,
  relativePath: string,
): Promise<void> {
  let currentPath = directory;
  for (const part of relativePath.split("/")) {
    currentPath = joinPath(currentPath, part);
    try {
      const info = await Deno.lstat(currentPath);
      if (info.isSymlink) {
        throw new Error(
          `Refusing to write through symlink "${currentPath}".`,
        );
      }
    } catch (error) {
      if (error instanceof Deno.errors.NotFound) {
        return;
      }
      throw error;
    }
  }
}

function joinPath(...parts: string[]): string {
  return parts.join("/").replaceAll(/\/+/g, "/");
}

function dirname(path: string): string {
  const index = path.lastIndexOf("/");
  return index < 0 ? "." : path.slice(0, index);
}
