name: Dev Container

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .devcontainer/**
      - .github/workflows/devcontainer.yml
      - .node-version
      - .tool-versions
      - package.json

permissions:
  contents: read
  packages: write

concurrency:
  group: devcontainer-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prebuild:
    name: Build and publish
    if: github.repository == 'zimme/bunny-edge-scripts'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Authenticate to GitHub Container Registry
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and publish development container
        uses: devcontainers/ci@513af61f4de4f75d37e4438f184ba4358f0fc1ca # v0.3.1900000450
        with:
          imageName: ghcr.io/zimme/bunny-edge-scripts-devcontainer
          imageTag: latest,${{ github.sha }}
          cacheFrom: ghcr.io/zimme/bunny-edge-scripts-devcontainer
          push: always
